// Minimal strings module to centralize user-facing text.

export const STRINGS = {
  registerVaultWithToken: "Register vault with token",
  registerAccountWithToken: "Register your account with token",
  transferring: "Transferring…",
  topUpToVault: (amount: string, symbol: string) => `Top up ${amount} ${symbol} to vault`,
  viewTokenOnExplorer: "View token on Explorer",
  viewVaultOnExplorer: "View vault on Explorer",
  copied: "Copied",
  copy: "Copy",
  vaultRegisteredSuccess: "Vault registered with token",
  accountRegisteredSuccess: "Registration successful",
  repaySuccess: "Loan repaid successfully",
  // Post-expiry (lender) dialog
  loanExpired: "Loan term ended",
  loanExpiredBodyIntro: "The loan associated with vault",
  totalDue: "Total due",
  vaultCollateral: "Vault collateral",
  beginLiquidation: "Start liquidation now",
  liquidationInProgress: "Liquidation in progress",
  continueProcessing: "Continue processing claims",
  liquidationGuideNote: "You can now begin the process to claim your funds from the vault collateral. This will walk you through the steps to submit your claim.",
  close: "Close",
  processing: "Processing…",
  processClaimsSuccess: "Liquidation claim processing started",
  processAvailableNow: "Process claims for available balance",
  whatHappensNext: "What happens next",
  willStartProcess: "The vault contract starts liquidation to pay your claim.",
  willContinueProcess: "The vault contract will continue liquidation to pay your claim.",
  attachesOneYocto: "This call attaches a 1 yoctoNEAR deposit and a small network fee.",
  mayTakeTime: "Parts of the process may take time (e.g., unstaking NEAR across epochs). You can close this window and return later.",
  mayTakeTimeContinuing: "Processing continues in steps (e.g., claiming matured funds). Some steps may take time across epochs.",
  trackProgressHere: "You can track progress in the 'Liquidation in progress' section on this page.",
  trackProgressHereInProgress: "Track updates in the 'Liquidation in progress' section below.",
  youCanCloseWindow: "You can safely close this window; processing will continue on-chain.",
  liquidationClosesRepay: "Starting liquidation closes the option and disables the owner's ability to repay directly.",
  willBePartial: "This will be a partial liquidation: only part of your claim is available now; the rest will be fulfilled as funds become available. You can run 'Process claims' again later.",
  willSettleNow: "Sufficient balance appears available to settle your claim now.",
  requirements: "Requirements",
  reqLenderOnly: "You must be the lender of this loan.",
  reqExpired: "The loan term must have ended, and it must not have been repaid.",
  safetyTitle: "Why this is safe",
  safetyYourKeys: "Only you can authorize this. Transactions are signed by your wallet using your private keys.",
  safetyContractChecks: "The smart contract verifies you are the lender and that the loan is eligible for liquidation.",
  safetyNoExtraFunds: "The call does not transfer your fungible tokens; it only attaches 1 yoctoNEAR and gas. Your funds remain under your control.",
  safetyCollateralBacked: "Your claim is fulfilled from the vault’s collateral and on-chain balances as defined by the contract.",
  safetyRetry: "If needed, you can safely retry later – the contract prevents unsafe or duplicate actions.",
  safetyOnChain: "Everything is recorded on-chain and can be reviewed in a block explorer.",
  // Appreciation copy for lenders
  lenderBadge: "Lender",
  lenderAppreciation: "You funded this request — thank you for supporting the ecosystem.",
  lenderLiquidationNote: "Your support is valued. We’re settling your claim from collateral as quickly as the network allows.",
  lenderGratitude: "Thank you for funding this loan — your participation powers real activity on the network.",
  liquidationInProgressIntro: "Liquidation is already in progress for vault",
  // Owner post-expiry messaging
  ownerBadge: "Vault owner",
  ownerRepayNow: "Repay now",
  ownerLoanExpiredIntro: "The loan for your vault has reached the end of its term:",
  ownerWhatYouCanDo: "What you can do",
  ownerCanRepay: "Repay the total due to avoid liquidation.",
  ownerLiquidationMayStart: "If you do not repay, the lender can begin liquidation and claim from your vault’s NEAR collateral.",
  ownerCollateralRisk: "Liquidation may progressively use your NEAR collateral until the lender’s claim is fully satisfied.",
  // Liquidation progress clarity
  waitingOnUnbondingTitle: "Unbonding status",
  waitingOnUnbondingBody: "Some collateral is currently unbonding. At the unlock epoch, the contract will claim matured funds and reduce the remaining amount owed to you by the expected amount shown below.",
  ownerWaitingOnUnbondingBody: "Some collateral is currently unbonding. At the unlock epoch, the contract will claim matured funds and reduce your remaining debt by the expected amount shown below.",
  expectedNextHint: "‘Expected next’ is what the contract can pay after claiming currently matured funds.",
  youCanRefresh: "Use Refresh to see updated maturity and availability.",
  refresh: "Refresh",
  // Payout destination clarity
  payoutDestination: "Payout destination",
  payoutsGoTo: "Payouts are sent directly to",
  viewAccountOnExplorer: "View account on Explorer",
  // Withdraw restrictions
  withdrawDisabledLiquidation: "Withdraw is disabled while liquidation is in progress.",
  withdrawDisabledActive: "Withdraw is disabled while a loan is active.",
  withdrawDisabledPending: "Withdraw is disabled while a liquidity request is open.",
  // Delegate restrictions
  delegateDisabledLiquidation: "Delegation is disabled while liquidation is in progress.",
  delegateDisabledRefunds: "Delegation is disabled while there are pending refund entries.",
  claimDisabledLiquidation: "Claim is disabled while liquidation is in progress.",
  undelegateDisabledLiquidation: "Undelegation is disabled while liquidation is in progress.",
  undelegateDisabledPending: "Undelegation is disabled while a liquidity request is open.",
  pendingRefunds: "Pending refunds",
  refundsAffectDelegation: "Delegation is temporarily unavailable until refunds are resolved.",
  // Simplified liquidation summary
  gettingYourMoney: "We’re getting your money back",
  paidSoFar: "Paid so far",
  expectedNext: "Expected next",
  availableNow: "Available now",
  nothingAvailableNow: "Nothing to claim right now",
  claimBecomesAvailable: "Claim will be available once funds mature.",
  waitingToUnlock: "Unlocking summary",
  showDetails: "Show details",
  hideDetails: "Hide details",
  nextPayoutSources: "Where the next payout comes from",
  sourceVaultBalanceNow: "Vault balance (available now)",
  sourceMaturedUnbonding: "Matured unbonding",
  noMaturedYet: "No matured entries yet",
  // Epoch / ETA labels
  unlockEpochLabel: "Unlock epoch",
  remainingLabel: "Remaining",
  etaLabel: "ETA",
  availableNowLabel: "Available now",
  // Note: dynamic strings should be implemented as functions outside STRINGS
  // Liquidation card: role-specific headings/notes
  ownerLiquidationHeader: "Paying lender from collateral",
  ownerLiquidationNote: "Liquidation is in progress to satisfy the lender’s claim using your vault’s NEAR.",
  unbondingFootnoteLender: "Unbonding completes when the unlock epoch is reached. These amounts will become available to reduce the remaining amount owed to you as soon as they mature. The contract will claim matured amounts during the liquidation flow. Epoch timing is network-defined and approximate.",
  unbondingFootnoteOwner: "Unbonding completes when the unlock epoch is reached. These amounts will become available to reduce your remaining debt as soon as they mature. The contract will claim matured amounts during the liquidation flow. Epoch timing is network-defined and approximate.",
};

/**
 * Returns the "Includes X NEAR matured" string.
 */
export function includesMaturedString(amount: string): string {
  return `Includes ${amount} NEAR matured`;
}
