name: NEAR Protocol Rewards Tracking
on:
  schedule:
    - cron: '0 0 * * *'     # Every 24 hours at midnight
  workflow_dispatch:        # Manual trigger
  push:
    branches: [ main ]     # Start on main branch updates

jobs:
  calculate-rewards:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      pull-requests: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Calculate Rewards
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          npm install -g near-protocol-rewards@latest
          near-protocol-rewards calculate
